export const typography = {
    lineHeights: {
        base: {
            display: "100%",
            headingExtraLarge: "110%",
            headingLarge: "140%",
            headingMedium: "140%",
            headingSmall: "140%",
            headingExtraSmall: "140%",
            headingExtraExtraSmall: "140%",
            subheading: "140%",
            subheadingSmall: "140%",
            eyebrow: "110%",
            p: "150%",
            smallp: "150%",
            disclaimer: "140%",
            leadp: "160%",
            largep: "140%",
            medium: "125%"
        },
        desktop: {
            display: "100%",
            headingExtraLarge: "110%",
            headingLarge: "140%",
            headingMedium: "140%",
            headingSmall: "140%",
            headingExtraSmall: "140%",
            headingExtraExtraSmall: "140%",
            subheading: "140%",
            subheadingSmall: "140%",
            eyebrow: "110%",
            p: "150%",
            smallp: "150%",
            disclaimer: "140%",
            leadp: "160%",
            largep: "140%",
            medium: "125%"
        },
        none: "none",
        70: "70%",
    },
    fontSizes: {
        base: {
            display: "2.75rem",
            headingExtraLarge: "2.125rem",
            headingLarge: "1.75rem",
            headingMedium: "1.625rem",
            headingSmall: "1.5rem",
            headingExtraSmall: "1.375rem",
            headingExtraExtraSmall: "1.25rem",
            subheading: "1.25rem",
            subheadingSmall: "1.125rem",
            eyebrow: "1.25rem",
            p: "1rem",
            smallp: ".875rem",
            disclaimer: ".75rem",
            leadp: "1.375rem",
            largep: "1.125rem",
            trademark: ".75rem",
            planData: "1.1875rem",
        },
        desktop: {
            display: "4.5rem",
            headingExtraLarge: "3.375rem",
            headingLarge: "2.5rem",
            headingMedium: "2.25rem",
            headingSmall: "2.125rem",
            headingExtraSmall: "1.75rem",
            headingExtraExtraSmall: "1.375rem",
            subheading: "1.5rem",
            subheadingSmall: "1.375rem",
            eyebrow: "1.5rem",
            p: "1.125rem",
            smallp: "1rem",
            disclaimer: ".875rem",
            leadp: "1.75rem",
            largep: "1.375rem",
            trademark: ".75rem",
            errorHeading: "6.875rem"
        },
    },
    fontFamilys: {
        titleFontFamily: "'Trade Gothic Next LT', 'proxima-nova'",
    },
};